# Generated by Django 4.1 on 2022-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_imported",
            field=models.BooleanField(default=False),
        ),
    ]
