# Generated by Django 4.1 on 2022-08-15 12:49

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_bio_user_cover_pic_user_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=apps.accounts.models.LowercaseCharField(
                error_messages={
                    "unique": "This email is not available, please try another one."
                },
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=300,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
