# Generated by Django 4.1 on 2022-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_password",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
