# Generated by Django 4.1 on 2022-08-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bio", models.CharField(blank=True, max_length=255, null=True)),
                ("fullname", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("screed_in", models.BooleanField(default=True)),
                (
                    "inbox",
                    models.CharField(
                        choices=[
                            ("IMBOX", "IMBOX"),
                            ("FEED", "FEED"),
                            ("PAPERTRAIL", "PAPERTRAIL"),
                        ],
                        default="IMBOX",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "msg_uid",
                    models.CharField(blank=True, max_length=3000000, null=True),
                ),
                ("to_users", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                ("received_datetime", models.DateTimeField(auto_now_add=True)),
                ("sent_datetime", models.DateTimeField(auto_now_add=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_received", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_trash", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to="imbox.emailaddress",
                    ),
                ),
            ],
        ),
    ]
